# Generated by Django 5.1.1 on 2024-10-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_alternativa_enunciado_alter_conteudo_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conteudo',
            name='topico',
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
