# Generated by Django 5.1.1 on 2024-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_conteudo_topico_delete_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
