<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_conteudo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
=======
# Generated by Django 5.1.1 on 2024-10-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_conteudo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
>>>>>>> c513ced (Primeio commit)
