# Generated by Django 5.1.2 on 2024-10-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_conteudo_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='alternativa_correta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corretas', to='app.alternativa'),
        ),
    ]
